### PR TITLE
bower support and touchups

### PR DESCRIPTION
**Pull request by acidjazz**
Bower support, if you merge this and want to point the registration back to your repo:
- modify bower.json and point it back to /abodelot/
- I believe you run `bower update` ? I could be wrong

### CODE REVIEW

**Comment by acidjazz** [comment]
- gave some spacing to the arrows and toned down the size and color
- added margin around the containing element so the 1st arrows were not hidden by default

image

**Comment by acidjazz** [comment]
Pointed the demo.html and readme.md to my fork, don't forget to point it back!

**Comment by tarampampam** [comment]
@abodelot will you apply this PR? We need bower supports too

**Comment by acidjazz** [comment]
@tarampampam i gave up years ago, use my version https://github.com/acidjazz/json-browse

**Comment by tarampampam** [comment]
@acidjazz Great thx 2 u!

**Comment by abodelot** [comment]
Hi,

Sorry, but I believe npm packaging should be enough, especially for a project this small.
You can just include files from `node_modules`.

-- Alexandre

**Pull request closed without merging**
