### PR TITLE
Defining html variable

### PR DESCRIPTION
**Pull request by PunxNotDead**
In strict mode we have this error: Uncaught ReferenceError: html is not defined

### CODE REVIEW

**Comment by abodelot** [comment]
Thanks!

**Comment by PunxNotDead** [comment]
@abodelot Can you update npm version?

**Comment by abodelot** [comment]
Hi! What do you mean by that?

There isn't any npm dependencies, and no npm version is enforced.

**Comment by PunxNotDead** [comment]
Hi,
I tried to install jquery.json-viewer as `npm i jquery.json-viewer`, and I have old version, without this change. But I'll try check it on other pc, may be it's my cache problem or something like this.
UPD: Checked, version in npm do not have fixes fron this PR.

**Pull request merged**
